name: generate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: generateAll
      run: |
        chmod 777 ./generateAll.sh
        chmod 777 ./generateDomain.sh
        ./generateAll.sh
