name: generate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: generateAll
      run: |
        chmod 777 ./generateAll.sh
        chmod 777 ./generateDomain.sh
        ./generateAll.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: localhost.crt
        path: out/localhost.crt

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: localhost.key
        path: out/localhost.key

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: localssl.crt
        path: out/localssl.crt
